apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-eks-restore
spec:
  storageClassName: ebs-sc
  dataSource:
    name: mysql-eks-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi