apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-eks-restore
spec:
  storageClassName: ebs-sc
  dataSource:
    name: wp-eks-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi